---
version: '2.1'
services:
  ravendb:
    image: ravendb/ravendb:4.2.4-ubuntu.18.04-x64
    hostname: ravendb
    container_name: ravendb
    ports:
      - "8080:8080"      
      - "38888:38888"
    # volumes:
      # - C:\Projetos\Docker Volumes\ravendb:/opt/RavenDB/config
      # - C:\Projetos\Docker Volumes\ravendb:/opt/RavenDB/Server/RavenData    
    environment:
      - RAVEN_Security_UnsecuredAccessAllowed=PublicNetwork
      - RAVEN_Setup_Mode=None      
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_ARGS='--log-to-console'
      
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    # volumes:
      # - C:\Projetos\Docker Volumes\elasticsearch:/usr/share/elasticsearch/data
    depends_on:
      - ravendb
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      xpack.security.enabled: "false"
      XPACK_SECURITY_ENABLED: "false"
      xpack.monitoring.enabled: "false"      
      discovery.type: "single-node"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.4.2
    hostname: kibana
    container_name: kibana
    # volumes:
      # - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    depends_on:
      elasticsearch:
        condition: service_healthy
    ports:
      - "5601:5601"          
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5601"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      xpack.security.enabled: "false"
      xpack_security_enabled: "false"
      xpack.monitoring.enabled: "false"
      discovery.type: "single-node"
      elasticsearch.url: http://elasticsearch:9200
      server.host: "0.0.0.0"
      server_host: "0.0.0.0"
      server.name: "kibana"
      server_name: "kibana"
      xpack_graph_enabled: "false"
      xpack_monitoring_enabled: "false"
      xpack_reporting_enabled: "false"
      xpack_security_enabled: "false"
      
  apm-server:
    image: docker.elastic.co/apm/apm-server:7.4.2
    hostname: apm-server
    container_name: apm-server    
    ports:
      - "8200:8200"    
    # volumes:
      # - ./apm-server.docker.yml:/usr/share/apm-server/apm-server.yml:ro
    depends_on:
      kibana:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8200"]
      interval: 10s
      timeout: 5s
      retries: 10
    environment:
      output.elasticsearch.hosts: "[elasticsearch:9200]"
      kibana.enabled: "true"
      kibana.host: "[kibana:5601]"  
      
  gerenciamentoprocessosjudiciais-jobs:
    image: archt/gerenciamentoprocessosjudiciais.jobs:8973
    hostname: gerenciamentoprocessosjudiciais-jobs
    container_name: gerenciamentoprocessosjudiciais-jobs
    depends_on:
      apm-server:
        condition: service_healthy    
    command: ["./wait-for-it.sh", "ravendb:8080", "--", "python", "app.py"]
    environment:      
      - RavenDbSettings__DatabaseName=GerenciamentoProcessosJudiciais
      - RavenDbSettings__Urls=http://ravendb:8080
      - ElasticSettings__Uri=http://elasticsearch:9200
      
  gerenciamentoprocessosjudiciais-api:
    image: archt/gerenciamentoprocessosjudiciais.api:8973
    hostname: gerenciamentoprocessosjudiciais-api
    container_name: gerenciamentoprocessosjudiciais-api
    ports:
      - "5002:80"
    depends_on:
      - gerenciamentoprocessosjudiciais-jobs    
    environment:
      - ElasticApm__LogLevel=Debug
      - ElasticApm__ServerUrls=http://apm-server:8200
      - ElasticApm__ServiceName=FT.GerenciamentoProcessosJudiciais.Api
      - ElasticApm__TransactionSampleRate=1.0
      - ElasticApm__CaptureHeaders=false
      - RavenDbSettings__DatabaseName=GerenciamentoProcessosJudiciais
      - RavenDbSettings__Urls=http://ravendb:8080